# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4e26d72e8211dd5dc413f09ce3f724d730f4b65577ec1403ee8fcec88ddd896c1beca6c45bd78c6541527e83d3c28672b5ff5e696e17a7173dccd3053d7546

test:
  secret_key_base: f66d78aca4cbf3f85f9ddd2b54a58a7eb7b4852303f327c0274a1d6b881edb9535ecffbb79481b66b6918039b36328761d0bea0303e9aa5abfaba0053a469632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
